name: CI / PhpStan
description: 'Run Php Stan'
inputs:
  token:
    description: 'The GitHub authentication token'
    default: ${{ github.token }}
  auth_json:
    description: 'The auth.json (for other bundles)'
    default: ''
runs:
  using: 'composite'
  steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Solves the not "You are not currently on a branch" problem, see https://github.com/actions/checkout/issues/124#issuecomment-586664611
          ref: ${{ github.event.pull_request.head.ref }}
          # Must be used to trigger workflow after push
          token: ${{ inputs.token }}

      - name: Add AUTH JSON
        shell: bash
        run: echo '${{ inputs.auth_json }}' > auth.json

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————
      - name: Validate composer.json and composer.lock
        run: composer validate
        shell: bash

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        shell: bash

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install
        shell: bash

      - run: vendor/bin/phpstan analyze src/
        shell: bash
        id: phpstan-check